[build]
publish = "public"
command = "hugo --gc --minify"

[build.environment]
HUGO_VERSION = "0.123.8"
GO_VERSION = "1.22.1"
NODE_VERSION = "20"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[context.deploy-preview]
command = "hugo --gc --minify -b $DEPLOY_PRIME_URL"

[context.branch-deploy]
command = "hugo --gc --minify -b $DEPLOY_URL"

[context.production]
command = "hugo --gc --minify"

[[redirects]]
  from = "/en/*"
  to = "/en/404.html"
  status = 404

[[redirects]]
  from = "/vi/*"
  to  = "/vi/404.html"
  status = 404

[[redirects]]
  from = "/*"
  to = "/en/404.html"
  status = 404
