name: Deploy Hugo to Netlify

on:
  push:
    branches:
      - main  # Hoặc branch mà bạn muốn trigger workflow

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: '0.140.2'  # Chỉ định phiên bản Hugo cụ thể, bạn có thể thay đổi phiên bản này theo yêu cầu của bạn

    - name: Build website
      run: hugo --config netlify.toml

    - name: Deploy to Netlify
      uses: nwtgck/actions-netlify@v2.0.0
      with:
        publish-dir: public
        production-deploy: true
      env:
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
