name: Deploy Hugo site to Netlify

on:
  push:
    branches:
      - master # or the branch you want to deploy

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: 'latest'

    - name: Build site
      run: hugo --minify

    - name: Deploy to Netlify
      uses: nwtgck/actions-netlify@v1.2.3
      with:
        publish-dir: ./public
        production-deploy: true
      env:
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
