name: Deploy to Netlify

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: latest
      - name: Build with Hugo
        run: hugo
      - name: Deploy to Netlify
        uses: netlify/actions/cli@v1
        with:
          args: deploy
          token: ${{ secrets.NETLIFY_AUTH_TOKEN }}
